#ifndef MACROS_N
#define MACROS_h

#define SENDERID 1
#define RECEIVERID 0


#define BIT(n) 1 << n

#define FLAG 0x7E
#define A_SR 0x03 //A Byte for commands sent by the transmmiter and asnwers sent by the receiver
#define C_UA 0x07 //C byte for UA answer given by the receiver
#define C_SET 0x03 //C byte for Setting the trame for the transmmiter

#define BCC(a,c) (a ^ c) //Bcc flag is generated by A Byte XOR with C byte




#endif
