#ifndef MACROS_N
#define MACROS_h

#define ALARM_INTERVAL 3 /* Time interval between triggering the signal */

#define SENDERID 1
#define RECEIVERID 0

#define DEBUG 1  /* Debug falg */


#define BIT(n) 1 << n   /* Bit mask */

#define FLAG 0x7E  /* Start and Stop trame byte */
#define A_SR 0x03  /* A byte for Sender to Receiver */
#define A_RS 0x01  /* A byte for Receiver to sender */
#define C_UA 0x07  /* Ua Trame Cfield */
#define C_SET 0x03  /* Set Trame CField */





#define BCC(a,c) (a ^ c) //Bcc flag is generated by A Byte XOR with C byte

#define ERROR -1  /* Error return type */
#define SUCESS 0 /* Sucess return type */

#endif
